/* Catalog logins — generated by build/make_user.mjs. Password hashes are
   PBKDF2-SHA256 (safe to commit). Never commit AUTH_SECRET — set it in Vercel. */
export default {
  "users": [
    {
      "u": "kuznetsov",
      "name": "Кузнецов В.Е. (владелец)",
      "role": "permanent",
      "expires": null,
      "salt": "MHNI5DrD2QOk8x1tz2ljNA",
      "hash": "3yDrtvs_TARva9x3UbFl5W1VyXWM3xq3SGeeZm4UPTo",
      "iters": 120000
    },
    {
      "u": "partner1",
      "name": "Пример: подрядчик",
      "role": "temporary",
      "expires": "2026-09-30",
      "salt": "dKQX0dDnHxDtY5xaMA9OSw",
      "hash": "gFYm7G_rZQ-ZoHcC5t-Y6srw6uI9xAOaLn7cWfjjs6c",
      "iters": 120000
    }
  ]
};
