/* Catalog logins — generated by build/make_user.mjs. Password hashes are
   PBKDF2-SHA256 (safe to commit). Never commit AUTH_SECRET — set it in Vercel. */
export default {
  "users": [
    {
      "u": "kuznetsov",
      "name": "Кузнецов В.Е. (владелец)",
      "role": "permanent",
      "expires": null,
      "salt": "YTf4TL7sK3Uj9IKXmOQS1g",
      "hash": "wW_m41YTnos1gyyQfxY2ZFbFntLZ88xu-UMSFUFDjRk",
      "iters": 120000
    },
    {
      "u": "partner1",
      "name": "Пример: подрядчик",
      "role": "temporary",
      "expires": "2026-09-30",
      "salt": "dKQX0dDnHxDtY5xaMA9OSw",
      "hash": "gFYm7G_rZQ-ZoHcC5t-Y6srw6uI9xAOaLn7cWfjjs6c",
      "iters": 120000
    }
  ]
};
