/* Catalog logins — generated by build/make_user.mjs. Password hashes are
   PBKDF2-SHA256 (safe to commit). Never commit AUTH_SECRET — set it in Vercel. */
export default {
  "users": [
    {
      "u": "kuznetsov",
      "name": "Кузнецов В.Е. (владелец)",
      "role": "permanent",
      "expires": null,
      "salt": "4M9_3bG9iNy90Cn1EKky_Q",
      "hash": "ROEGh8oPWNQ_cdBBOgbXltuwjzD8xV4OdJ3IchlHBcg",
      "iters": 120000
    },
    {
      "u": "user",
      "name": "Временный доступ",
      "role": "temporary",
      "expires": "2026-09-22",
      "salt": "drHOd3NVbE1zfF01PSJOxw",
      "hash": "y8GsbWNbDC1-DcOa7NCsH3JZrL8ty2w6oVx8K19x4Es",
      "iters": 120000
    }
  ]
};
